### ISSUE TITLE
displaying the duration of the phases

### ISSUE THREAD

**Issue by Se1en** [ospin-web-dev/non-repo-issues#76] opened 2020-10-29 15:10 UTC
All information you provide is helpful to us! Thank you for taking the time.

### Describe the feature / change request
Would it be possible to show exact time spent in a phase? ideally all of them, not just some?
e.g. i run process consisting of multiple phases, because i ... e.g. change setting, or pause or ... yeah, lets call it 'execute a change'. 

e.g. change request:
Currently, when any change is executed it is possible to either read it from the graph (wild guess), (from the builder, if it is a phase in the middle of the process), in configuration or the process log (if you try really hard). the duration of the first and the last phase is not printed anywhere though. and process log is a bit difficult way of displaying info.
Could you please show the duration of all phases under its names or on the top of the data page for each phase? or at least in the configuration? even for the manually set phases?

https://staging.ospin-app.com/device/6146a711-accf-422a-a70d-910ada0d765e/process/beb2f6ca-03dd-4c5b-9e12-5b53707a74d8

### Screenshots
for example, i have 4 phases here (1). and even though you can see the duration of phases that were switched (2), you still have to calculate (or just guess, because you are lazy) what was the time spent in the first (3) and the last phase (4)
1 ![image](https://user-images.githubusercontent.com/73227192/97587000-344ed780-19fb-11eb-9148-45ba9e80b408.png)

2 ![image](https://user-images.githubusercontent.com/73227192/97587321-8abc1600-19fb-11eb-8a0a-2f4cadf9e03a.png)

3 ![image](https://user-images.githubusercontent.com/73227192/97591794-43845400-1a00-11eb-9c0b-3dbb402b6ece.png)

4 ![image](https://user-images.githubusercontent.com/73227192/97591726-323b4780-1a00-11eb-9107-975b62731a3d.png)

no number for the manually set phases. also, i do not understand, why it says, that the phases 1 and 1* were on duration mode, when i manually changed those. one does not simply set a phase to last 37seconds. 
![image](https://user-images.githubusercontent.com/73227192/97588119-775d7a80-19fc-11eb-9f89-e40c25528a13.png)

### Additional context
calculating and subtracting time is difficult. 😭 
thank you! <3 <3 <3

**Comment by DanielSeehausen** [comment] 2020-10-30 16:55
This was selected for development. This ticket itself I am closing as a duplicate of another, which has already been transferred to the appropriate repo and triaged! 

https://github.com/ospin-web-dev/REACTor/issues/1100

**Closed by DanielSeehausen** 2020-10-30 16:55 UTC
Labels: feature, triage required
